/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/assets/ThreeD/ModularToolAttachments.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function ModularToolAttachments(props) {
  const { nodes, materials } = useGLTF('../../../assets/ThreeD/ModularToolAttachments.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Body32.geometry} material={materials.texture_2} position={[0.181, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body36.geometry} material={materials.texture_2} position={[0.181, 0.346, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body56.geometry} material={materials.texture_2} position={[-0.178, 0.346, -0.254]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body60.geometry} material={materials.texture_2} position={[-0.178, 0.346, 0.355]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body76.geometry} material={materials.texture_2} position={[-0.178, 0.068, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body78.geometry} material={materials.texture_2} position={[0.181, 0.068, 0.285]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body110.geometry} material={materials.texture_2} position={[0.191, 0.069, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body113.geometry} material={materials.texture_2} position={[-0.189, 0.069, 0.287]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body6001.geometry} material={materials.texture_2} position={[-0.186, 0.286, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body10001.geometry} material={materials.texture_2} position={[0.188, 0.286, -0.363]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body15001.geometry} material={materials.texture_2} position={[-0.186, 0.346, -0.269]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body16001.geometry} material={materials.texture_2} position={[-0.186, 0.345, -0.284]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Body8002.geometry} material={materials.texture_2} position={[-0.186, 0.344, 0.382]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <group position={[0.562, 0.594, 0.361]} rotation={[0, -0.262, 0]}>
        <mesh geometry={nodes['Body1_(1)002'].geometry} material={materials.texture} />
        <mesh geometry={nodes['Body1_(1)002_1'].geometry} material={materials.Steel} />
        <mesh geometry={nodes['Body1_(1)002_2'].geometry} material={materials.black_metal} />
        <group position={[0.069, 0.083, 0.064]} rotation={[-0.609, -0.001, 0.004]} scale={0.001}>
          <mesh geometry={nodes.body2002_1.geometry} material={materials.texture} />
          <mesh geometry={nodes.body2002_2.geometry} material={materials.Steel} />
          <mesh geometry={nodes.body2002_3.geometry} material={materials.black_metal} />
          <mesh geometry={nodes.body2002_4.geometry} material={materials['Material.001']} />
          <group position={[-33.7, 305, 0]} rotation={[0.018, 0, 0]}>
            <mesh geometry={nodes.body4_002_1.geometry} material={materials.texture} />
            <mesh geometry={nodes.body4_002_2.geometry} material={materials.Steel} />
            <mesh geometry={nodes.body4_002_3.geometry} material={materials.black_metal_1} />
            <group position={[-36.2, 0, 41.341]} rotation={[-0.083, 0.028, -0.031]}>
              <mesh geometry={nodes.body4_003_1.geometry} material={materials.texture} />
              <mesh geometry={nodes.body4_003_2.geometry} material={materials.black_metal} />
              <group position={[15.718, 0, 182.3]} rotation={[-0.044, -0.001, 0.001]}>
                <mesh geometry={nodes.body5002_1.geometry} material={materials.texture} />
                <mesh geometry={nodes.body5002_2.geometry} material={materials.black_metal} />
                <mesh geometry={nodes.body5002_3.geometry} material={materials['Steel - Satin.001']} />
                <mesh geometry={nodes.Body109001.geometry} material={materials.black_metal_1} position={[15.194, -15.546, 50.107]} rotation={[-0.629, 0, 0]} />
                <group position={[-17.303, -36.815, 45.031]} rotation={[-0.629, 0, 0]}>
                  <mesh geometry={nodes.box_pcb001_1.geometry} material={materials.texture} />
                  <mesh geometry={nodes.box_pcb001_2.geometry} material={materials.orange} />
                  <mesh geometry={nodes.box_pcb001_3.geometry} material={materials.black_metal_1} />
                </group>
                <mesh geometry={nodes.jaw_2001.geometry} material={materials.black_metal_1} position={[-7.008, -152.807, 113.992]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.logo_cap001.geometry} material={materials.texture} position={[-20.788, -17.107, 59.707]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.logo_scale001.geometry} material={materials.orange} position={[-19.83, -14.006, 63.532]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.servo_cap001.geometry} material={materials.black_metal_1} position={[-32.362, -59.225, 38.932]} rotation={[-0.629, 0, 0]}>
                  <mesh geometry={nodes.Body1003.geometry} material={materials.black_metal_1} position={[5.079, -100.03, 0.436]} />
                  <mesh geometry={nodes.jaw_1001.geometry} material={materials.black_metal_1} position={[-17.628, -119.832, -5.36]} />
                  <mesh geometry={nodes.shaft_b001.geometry} material={materials.Steel} position={[0.005, -42.08, 0.025]} />
                </mesh>
                <mesh geometry={nodes['servo_real_(1)001'].geometry} material={materials['Opaque(245,245,246)']} position={[-23.248, -46.62, 29.687]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.servo_real001.geometry} material={materials.black_metal_1} position={[-23.247, -117.885, 82]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.shaft_a001.geometry} material={materials.Steel} position={[-32.362, -70.91, 47.429]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes['SLIP_RING_HOLDER_(1)001'].geometry} material={materials.black_metal_1} position={[-23.292, -63.312, 46.526]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.SLIP_RING001.geometry} material={materials.Steel} position={[-32.362, -76.568, 51.584]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.TOP_servo_cap001.geometry} material={materials.black_metal_1} position={[-22.873, -35.177, 20.365]} rotation={[-0.629, 0, 0]} />
                <mesh geometry={nodes.tpu_cover001.geometry} material={materials.black_metal_1} position={[-2.369, -170.34, 119.949]} rotation={[-0.629, 0, 0]} />
              </group>
            </group>
          </group>
          <mesh geometry={nodes.Curve003.geometry} material={materials.orange} position={[19.05, 281.868, 0.5]} scale={1000} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../../../assets/ThreeD/ModularToolAttachments.glb')